=== Aleksandr-Mazhul/mazhul-web-development/web-design-semester-2/xml/library.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="GenreType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Fantasy"/>
            <xs:enumeration value="Science"/>
            <xs:enumeration value="History"/>
            <xs:enumeration value="Programming"/>
            <xs:enumeration value="Novel"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="LanguageType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="English"/>
            <xs:enumeration value="Russian"/>
            <xs:enumeration value="German"/>
            <xs:enumeration value="French"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CoverType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hard"/>
            <xs:enumeration value="Soft"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="BookCodeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="BK-[A-Z]{2}-[0-9]{3}-[a-z]{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="PublisherType">
        <xs:attribute
                name="id"
                type="xs:ID"
                use="required"/>

        <xs:attribute
                name="name"
                type="xs:string"
                use="required"/>
    </xs:complexType>

    <xs:complexType name="BookType">

        <xs:sequence>
            <xs:element
                    name="title"
                    type="xs:string"/>

            <xs:element
                    name="genre"
                    type="GenreType"/>

            <xs:element
                    name="year"
                    type="xs:gYear"/>
        </xs:sequence>

        <xs:attribute
                name="id"
                type="xs:ID"
                use="required"/>

        <xs:attribute
                name="bookCode"
                type="BookCodeType"
                use="required"/>

        <xs:attribute
                name="author"
                type="xs:string"
                use="required"/>

        <xs:attribute
                name="cover"
                type="CoverType"
                use="optional"/>

        <xs:attribute
                name="language"
                type="LanguageType"
                default="English"/>

        <xs:attribute
                name="publisherRef"
                type="xs:IDREF"
                use="required"/>

        <xs:attribute
                name="pages"
                use="required">

            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="50"/>
                    <xs:maxInclusive value="2000"/>
                </xs:restriction>
            </xs:simpleType>

        </xs:attribute>

    </xs:complexType>

    <xs:element name="library">

        <xs:complexType>

            <xs:sequence>

                <xs:element
                        name="publisher"
                        type="PublisherType"
                        maxOccurs="unbounded"/>

                <xs:element
                        name="book"
                        type="BookType"
                        maxOccurs="unbounded"/>

            </xs:sequence>

        </xs:complexType>

    </xs:element>

</xs:schema>

=== Aleksandr-Mazhul/mazhul-web-development/web-design-semester-2/xml/library.xml
<?xml version="1.0" encoding="UTF-8"?>

<library
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="library.xsd">

    <publisher
            id="pub1"
            name="Penguin"/>

    <publisher
            id="pub2"
            name="OReilly"/>

    <publisher
            id="pub3"
            name="Springer"/>

    <book
            id="b1"
            bookCode="BK-CS-101-ab"
            author="John Smith"
            cover="Hard"
            language="English"
            publisherRef="pub1"
            pages="320">

        <title>XML Basics</title>
        <genre>Programming</genre>
        <year>2020</year>

    </book>

    <book
            id="b2"
            bookCode="BK-HT-205-cd"
            author="Anna Brown"
            cover="Soft"
            language="German"
            publisherRef="pub2"
            pages="540">

        <title>World History</title>
        <genre>History</genre>
        <year>2018</year>

    </book>

    <book
            id="b3"
            bookCode="BK-SC-310-ef"
            author="Robert White"
            cover="Hard"
            language="English"
            publisherRef="pub3"
            pages="410">

        <title>Physics Today</title>
        <genre>Science</genre>
        <year>2021</year>

    </book>

    <book
            id="b4"
            bookCode="BK-NV-120-gh"
            author="Emily Green"
            cover="Soft"
            language="French"
            publisherRef="pub1"
            pages="270">

        <title>Silent River</title>
        <genre>Novel</genre>
        <year>2019</year>

    </book>

    <book
            id="b5"
            bookCode="BK-FA-450-ij"
            author="Michael King"
            cover="Hard"
            language="English"
            publisherRef="pub2"
            pages="690">

        <title>Dragon Empire</title>
        <genre>Fantasy</genre>
        <year>2022</year>

    </book>

    <book
            id="b6"
            bookCode="BK-CS-777-kl"
            author="David Stone"
            cover="Soft"
            language="Russian"
            publisherRef="pub3"
            pages="860">

        <title>Advanced Programming</title>
        <genre>Programming</genre>
        <year>2023</year>

    </book>

    <book
            id="b7"
            bookCode="BK-SC-555-mn"
            author="Sophia Adams"
            cover="Hard"
            language="English"
            publisherRef="pub1"
            pages="190">

        <title>Biology Guide</title>
        <genre>Science</genre>
        <year>2017</year>

    </book>

    <book
            id="b8"
            bookCode="BK-NV-888-op"
            author="Daniel Young"
            cover="Soft"
            language="German"
            publisherRef="pub2"
            pages="350">

        <title>Lost Memories</title>
        <genre>Novel</genre>
        <year>2016</year>

    </book>

</library>
